services:
  - type: web
    name: deepfake-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn your_project_name.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: your_project_name.settings
      - key: PYTHON_VERSION
        value: 3.9