services:
  - type: web
    name: deepfake-backend
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn deepfake_backend.wsgi
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: deepfake_backend.settings
      - key: PYTHON_VERSION
        value: 3.9.13